# Generated by Django 3.0.2 on 2020-01-15 14:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('web', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['content_search'], name='web_page_content_505071_gin'
            ),
        ),
    ]
