# Generated by Django 3.0.2 on 2020-01-16 13:23

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_create_trigram_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content_search',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
